name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ lnvkLTRcqF__yDZM7GDK0mV6HV4H3LDV7LqJkzE9 }}
          accountId: ${{ aa7b007a2c2d9357a6dd44d6a6e044b2 }}
          projectName: zeroscansecurity
          directory: ./
